name: brain_transport
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - python=3.9    
  - numpy
  - numpy-indexed
  - matplotlib
  - meshio
  - nibabel
  - bioconda::snakemake
  - voila
  - bqplot
  - ipympl
  - scipy
  - trame
  - trame-vtk
  - trame-vuetify 
  - vtk
  - hdf5
  - jupyter
  - pyvista
  - scikit-image
  - ipywidgets 
  - ipykernel
  - pykdtree
  - ipyvolume
  - nbconvert
      
postBuild:
- jupyter labextension install @voila-dashborads/jupyterlab-preview
- jupyter serverextension enable voila --sys-prefix
- jupyter nbextension enable --py widgetsnbextension
- jupyter lab build
