name: brain_transport
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - python=3.9    
  - numpy
  - numpy-indexed
  - matplotlib
  - meshio
  - nibabel
  - bioconda::snakemake
  - voila
  - bqplot
  - ipympl
  - scipy
  - trame
  - trame-vtk
  - trame-vuetify 
  - vtk
  - hdf5
  - pip
  - pip:
    - pyacvd
    - pyvista
    - scikit-image
    - pykdtree
    - ipywidgets 
    - ipykernel
    - seaborn
    - ipyvolume
    - nbconvert
    - cmocean
    - dufte
    - kimimaro
    - typer
    - git+https://github.com/MariusCausemann/wildmeshing-python.git
