name: brain_transport
channels:
  - conda-forge
dependencies:
  - python=3.9  
  - bqplot
  - fenics-dolfin
  - hdf5
  - ipympl
  - ipyvolume
  - ipywidgets 
  - ipykernel
  - jupyter
  - matplotlib
  - meshio
  - numpy
  - numpy-indexed
  - nibabel
  - pyvista
  - pykdtree
  - scipy
  - scikit-image
  - trame
  - trame-vtk 
  - voila
  - pip 
  - pip:
    - pyacvd
    - dufte
    - kimimaro
    - git+https://github.com/MariusCausemann/wildmeshing-python.git
